# Generated by Django 4.0.5 on 2022-07-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('precioProducto', models.IntegerField()),
                ('descripcionProducto', models.TextField(max_length=300)),
            ],
        ),
    ]
