# Generated by Django 4.0.5 on 2022-07-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idPromocion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePromocion', models.CharField(max_length=40)),
                ('porcentaje', models.IntegerField()),
                ('fecha_ini', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
            ],
        ),
    ]
